dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - scikit-image
    - matplotlib
    - thinc
    - torch
    - torchvision
    - opencv-python
    - opencv-contrib-python
    - runway-python
    - gdown
    - pillow
